[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "RBEdu"
description = ""
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "omni.isaac.etri_env"

[[python.module]]
name = "RBEdu_python"

[[python.module]]
name = "RBEdu_python.HelloAsset"

[[python.module]]
name = "RBEdu_python.HelloProperty"

[[python.module]]
name = "RBEdu_python.HelloDeformable"

[[python.module]]
name = "RBEdu_python.HelloRandomBox"

[[python.module]]
name = "RBEdu_python.HelloLight"

[[python.module]]
name = "RBEdu_python.HelloCamera"

[[python.module]]
name = "RBEdu_python.HelloLilLibrary" 

[[python.module]]
name = "RBEdu_python.HelloEnvRandomizer"

[[python.module]]
name = "RBEdu_python.HelloMDLMaterial"

[[python.module]]
name = "RBEdu_python.HelloOmniGlass"

[[python.module]]
name = "RBEdu_python.HelloManipulator"

[[python.module]]
name = "RBEdu_python.HelloCustomGripper"

[[python.module]]
name = "RBEdu_python.HelloRoboData"

[[python.module]]
name = "RBEdu_python.ReplicatorBasic"


[[python.module]]
name = "RBEdu_python.HelloMobileRobot"

[[python.module]]
name = "RBEdu_python.HelloWorld"

